module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testRegex: "src/.*\\.(test|spec)?\\.(ts|tsx)$",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.ts"],
  coveragePathIgnorePatterns: [
    "src/@lib/@types/index.ts",
    "src/@lib/cmd/index.ts",
    "src/@lib/errors/index.ts",
    "src/@lib/errors/markdown.ts",
    "src/@lib/metrics",
    "src/@lib/logger.ts",
    "src/@lib/prisma.ts",
    "src/@lib/index.ts",
    "src/auth/index.ts",
    "src/ezpr/index.ts",
    "src/ezpr/listeners",
    "src/help/index.ts",
    "src/help/listeners",
    "src/app.ts",
    "src/appConfig.ts",
    "src/constants.ts",
    "src/handlers.ts",
  ],
  coverageThreshold: {
    global: {
      statements: 75.86,
      branches: 52.34,
      lines: 75.33,
      functions: 63.29,
    },
  },
};
