org: jcserv
app: ez-pr-bot
service: slack-bolt-app
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    NODE_ENV: ${env:NODE_ENV}
    USER_ID: ${env:USER_ID}
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
