service: serverless-bolt-ts
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    USER_ID: ${env:USER_ID}
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
