name: EZ PR Bot
url: https://ezprbot.com/
description: A Slack bot that accelerates your team's PR review process
public: false

default_events:
  - check_suite
  - pull_request
  - pull_request_review
  - pull_request_review_comment
  - pull_request_review_thread
  - push

default_permissions:
  checks: read
  contents: read
  metadata: read
  pull_requests: write
