org: jcserv
app: ez-pr-bot
service: github
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  environment:
    NODE_ENV: ${env:NODE_ENV}
    APP_ID: ${env:APP_ID}
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    DYNAMO_TABLE: ${env:DYNAMO_TABLE}
    REGION: ${aws:region}
  iam:
    role:
      statements:
        - ${file(../../resources/BaseLambdaRole.yml):dynamoRWAccessPolicy}

package:
  individually: true

functions:
  events:
    handler: functions/eventListener/handler.events
    events:
      - http:
          path: events
          method: post
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(../../resources/SlackEventListenerLambdaRole.yml):eventListenerCloudwatchMetricsPolicy}
    warmup:
      officeHoursWarmer:
        enabled: false

  getPrs:
    handler: functions/prs/handler.getPrs
    events:
      - http:
          path: prs
          method: get
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(../../resources/SlackEventListenerLambdaRole.yml):eventListenerCloudwatchMetricsPolicy}
    warmup:
      officeHoursWarmer:
        enabled: false

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    excludeFiles: "**/*.test.ts"

  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *) # Run WarmUp every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
      concurrency: 10
      verbose: false

  customDomain:
    domainName: api.ezprbot.com
    basePath: "github"
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-iam-roles-per-function
  - serverless-domain-manager
