org: jcserv
app: ez-pr-bot
service: github
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  environment:
    NODE_ENV: ${env:NODE_ENV}
    APP_ID: ${env:APP_ID}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    LOG_LEVEL: ${env:LOG_LEVEL}
    WEBHOOK_PROXY_URL: ${env:WEBHOOK_PROXY_URL}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    DYNAMO_TABLE: ${env:DYNAMO_TABLE}
    REGION: ${aws:region}
  iam:
    role:
      statements:
        - ${file(../../resources/BaseLambdaRole.yml):dynamoRWAccessPolicy}

package:
  individually: true

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    excludeFiles: "**/*.test.ts"

  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *) # Run WarmUp every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
      concurrency: 10
      verbose: false

functions:
  events:
    handler: functions/eventListener/handler.events
    events:
      - http:
          path: github/events
          method: post
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(../../resources/SlackEventListenerLambdaRole.yml):eventListenerCloudwatchMetricsPolicy}
    warmup:
      officeHoursWarmer:
        enabled: false

  # oauth:
  #   handler: functions/oauth/handler.oauth
  #   events:
  #     - http:
  #         path: github/oauth_redirect
  #         method: get
  #   iamRoleStatementsInherit: true
  #   warmup:
  #     officeHoursWarmer:
  #       enabled: false

  # install:
  #   handler: functions/oauth/handler.oauth
  #   events:
  #     - http:
  #         path: github/install
  #         method: get
  #   iamRoleStatementsInherit: true
  #   warmup:
  #     officeHoursWarmer:
  #       enabled: false

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-iam-roles-per-function
